### ISSUE TITLE
[Bug] Neither reading articles nor discovering feeds works for most sites

### ISSUE THREAD

**Issue by gilamori** [dauphine-dev/drop-feeds#105]
#### System: 
 * Operating System:  Windows 10
 * Firefox: 65.0 (but I've had the same problem since at least v60.)

#### What should happen:
When I click a Drop Feeds link to the left, the page's feed should open in the browser so I can read it. If I click the "discover feeds" icon, the popup should show a list of feeds (provided that there are any).

#### What actually happened:
For most sites, Drop Feeds gets stuck at "Loading [page]", and I never get to read the content. Some rare sites, like xkcd.com and news.ycombinator.com always work. I can see no relevant difference in the HTML that would explain why some sites work and others don't. If I try to discover feeds, the "Discovering feeds" bar stops at 97% or so, and no feeds appear (except for the same, rare sites like xkcd.com).

#### Steps to reproduce:
I have no idea. The browser works normally otherwise. The problem remains even if I disable all other extensions. The things I may be doing differently than most people are 1: having a very long RSS list (inherited from Sage RSS), and having many (30+) windows open at the same time. Any ideas for troubleshooting?

**Comment by dauphine-dev** [comment]
Hi @gilamori welcome,
 * Please can you provide an url of a feed with the issue "I never get to read the content" ?
 * And an url of a site where Discovering feeds is stuck at 97% (I have fixed a bug like that in a Drop feeds 0.9.3a, may be you don't have the last version Drop Feeds 0.9.4 ?)
  * When you say "and having many (30+) windows open at the same time" you mean 30 Firefox windows, or 30 windows of any applications ?

(I have too a very long RSS list inherited from Sage RSS, more than 600)

Thank you for the report.

**Comment by gilamori** [comment]
Thank you for the quick response!

Well, bleedingcool.com and slashdot.org are two (out of hundreds) that I can't read via Drop Feeds. If I right-click the Drop Feeds links and choose "info", the direct links to feeds are: http://www.bleedingcool.com/feed/ and http://rss.slashdot.org/Slashdot/slashdot . 

If I go to bleedingcool.com or slashdot.org and try to discover feeds, then the progress bar stops just before the end and no feeds appear in the pop-up window. I can discover feeds on xkcd.com or lemonde.fr, though, so it seems that both problems are related and appear (or don't appear) on the same sites.

I use 0.9.4, but I had the same problem with the previous versions. (Although back when I used Firefox fifty-something with an earlier version of Drop Feeds, I was able to read content, but not discover feeds).

Over 30 Firefox windows (which at first led me to believe that it could be some kind of memory/processor/thread-related problem, but now that I think about it, the fact that xkcd.com and lemonde.fr work flawlessly indicates that that isn't the case, so I'm not sure that me having many windows open is relevant at all).

**Comment by gilamori** [comment]
One clarification: I mistakenly thought I had used lemonde.fr as one of my first examples of sites that I was able to read, which is why I used it as an example in my new comment ten minutes ago. So what I'm trying to say is that xkcd.com, lemonde.fr and news.ycombinator.com all work for me in Drop Feeds, while for nearly every other site, feeds are both unreadable and un-discoverable.

Sorry about the confusing wording!

**Comment by dauphine-dev** [comment]
For information sites declare RSS feeds in the header and to subscribe to them you have to use the button "Subscribe".
![image](https://user-images.githubusercontent.com/36274213/52467517-189c0180-2b86-11e9-837e-b93f9090cf14.png)
![image](https://user-images.githubusercontent.com/36274213/52467525-1c2f8880-2b86-11e9-8c32-5170b852ce76.png)

The button "Discovering feeds" try to found undeclared feeds, by looking all links in the page, and with a regex try to identify which one can be a feed, and then download documents pointed by theses links, and try to parse them as feed, and if the parse works then the link is added to the discovered feeds list.

Most of sites are Feed links declared properly in the header and you get nothing from "Discovering feeds".

You should use the "Subscribe" button 1st, and if you get nothing, then try the "Discovering feeds" button. But any way it shouldn't be stuck at 97% since version 0.9.3a (can you confirm ?). May be an improvement that I can do ; it is add feed links declared properly in the discovered feeds list too.

About unreadable feeds, it can be because a bugged settings, and I have probably different settings than yours, then can you paste a screen of your settings, specially for tabs Items, Content area, and Theme
![image](https://user-images.githubusercontent.com/36274213/52468248-6f0a3f80-2b88-11e9-9703-004a0beee9d8.png)

**Comment by gilamori** [comment]
Oops, clearly I should have been using "Subscribe" instead. Regarding the unreadable feeds, I've attached a picture of my settings.
![dropf](https://user-images.githubusercontent.com/26882641/52502326-cccb7580-2be2-11e9-9eed-41aa9a6de314.png)

**Comment by dauphine-dev** [comment]
Arg, in fact we are using same settings, then I have no idea :-(
 * Then [open the console](https://github.com/dauphine-dev/drop-feeds/wiki/How-to-display-the-debug-console-%3F) and clear it.
 * Click on an unreadable feed to try to open it
 * Copy messages from console and paste them in this thread

**Comment by gilamori** [comment]
The console shows nothing at all.

**Comment by dauphine-dev** [comment]
Try Drop feeds 0.9.5rc1 in this version I have fixed some thing similar for Firefox 67 because an issue with API `history.getVisits` ,  may be you have a setting in about:config (or an other addon) that is blocking this API.
If it is the case it should be worked with Drop feeds 0.9.5rc1.

**Comment by dauphine-dev** [comment]
Drop feeds 0.9.5rc1 is here:
https://github.com/dauphine-dev/drop-feeds/releases

**Comment by gilamori** [comment]
0.9.5rc1 made no difference, but I found an extension to save the URLS of the 500+ tabs I had open, reinstalled Firefox from scratch, and now Drop Feeds works. So I'm still not sure what caused the problem, but it seems to be gone now. Thank you for all your help! 

(And if you ever get the time, please add an option to Drop Feeds so users can use their own CSS file to style the content).

**Comment by dauphine-dev** [comment]
I guess that it was a settings in about:config, but we will never know for sure...

About CSS, I will do a theme editor, but is a big work, then I need to found time to do it.

I close this issue ;-)
